[package]
name = "greentic-messaging-test"
version.workspace=true
edition = "2024"
description = "Interactive tool to run MessageCard fixtures across Teams/Webex/Slack/WebChat/Telegram/WhatsApp translations."
license = "MIT"

[package.metadata.binstall]
pkg-url = "https://github.com/greentic-ai/greentic-messaging/releases/download/v{ version }/greentic-messaging-test-{ target }.{ archive-format }"
pkg-fmt = "tgz"
pkg-fmt-windows = "zip"
targets = [
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-pc-windows-msvc",
]

[dependencies]
anyhow = "1"
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }
greentic-types = { workspace = true }
greentic-flow = { workspace = true }
greentic-pack-lib = { workspace = true }
greentic-distributor-client = { version = "0.4", features = ["dist-client"] }
blake3 = "1"
gsm-core = { workspace = true }
gsm-telemetry = { workspace = true }
secrets-core = { workspace = true }
gsm-translator = { workspace=true }
tempfile = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
indexmap = "2"
semver = "1"
tempfile = { workspace = true }
