[package]
name = "greentic-messaging-test"
version.workspace=true
edition = "2024"
description = "Interactive tool to run MessageCard fixtures across Teams/Webex/Slack/WebChat/Telegram/WhatsApp translations."
license = "MIT"

[dependencies]
anyhow = "1"
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }
greentic-types = { workspace = true }
gsm-core = { workspace = true }
gsm-telemetry = { workspace = true }
greentic-secrets = { workspace = true }
gsm-translator = { workspace=true }
tempfile = { workspace = true }
