[package]
name = "greentic-messaging-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync"] }
greentic-types = { workspace = true }
greentic-interfaces = { workspace = true }
gsm-core = { workspace = true }
gsm-telemetry = { workspace = true }
greentic-secrets = { workspace = true }
gsm-translator = "0.3.6"
tempfile = { workspace = true }
