[package]
name = "nats-demo"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "nats-demo"
path = "src/main.rs"

[dependencies]
greentic-types = { workspace = true }
anyhow = { workspace = true }
async-nats = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
gsm-telemetry = { workspace = true }
gsm-core = { path = "../../libs/core" }
futures = { workspace = true }
