[package]
name = "gsm-ingress-webchat"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Greentic messaging package: ingress webchat."
readme = "../../README.md"
repository = "https://github.com/greentic-ai/greentic-messaging"
homepage = "https://github.com/greentic-ai/greentic-messaging"
publish = false

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
greentic-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-nats = { workspace = true }
time = { workspace = true }
gsm-core = { path = "../../libs/core" }
gsm-ingress-common = { path = "../ingress-common" }
gsm-idempotency = { path = "../../libs/idempotency" }
gsm-dlq = { path = "../../libs/dlq" }
include_dir = { workspace = true }
security = { workspace = true }
gsm-telemetry = { workspace = true }
metrics = { workspace = true }
