[package]
name = "gsm-ingress-webex"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Greentic messaging package: ingress webex."
readme = "../../README.md"
repository = "https://github.com/greentic-ai/greentic-messaging"
homepage = "https://github.com/greentic-ai/greentic-messaging"
publish = false

[features]
legacy = []

[[bin]]
name = "gsm-ingress-webex"
path = "src/main.rs"
required-features = ["legacy"]

[dependencies]
anyhow = { workspace = true }
async-nats = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
greentic-types = { workspace = true }
time = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
sha1 = { workspace = true }
subtle = { workspace = true }
hex = { workspace = true }
async-trait = { workspace = true }
gsm-core = { path = "../../libs/core", features = ["legacy"] }
gsm-idempotency = { path = "../../libs/idempotency" }
gsm-ingress-common = { path = "../ingress-common" }
gsm-telemetry = { workspace = true }
gsm-translator = { path = "../../libs/translator" }
metrics = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
axum = { workspace = true, features = ["macros"] }
tower = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
