[package]
name = "gsm-ingress-telegram"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Greentic messaging package: ingress telegram."
readme = "../../README.md"
repository = "https://github.com/greentic-ai/greentic-messaging"
homepage = "https://github.com/greentic-ai/greentic-messaging"
publish = false

[features]
legacy = []

[[bin]]
name = "gsm-ingress-telegram"
path = "src/main.rs"
required-features = ["legacy"]

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
greentic-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-nats = { workspace = true }
time = { workspace = true }
gsm-core = { path = "../../libs/core", features = ["legacy"] }
gsm-ingress-common = { path = "../ingress-common" }
gsm-dlq = { path = "../../libs/dlq" }
gsm-idempotency = { path = "../../libs/idempotency" }
security = { workspace = true }
gsm-telemetry = { workspace = true }
metrics = { workspace = true }
serde_yaml_bw = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tracing-test = { workspace = true }
